### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [csurally/prj-rev-bwfs-dasmoto#6]
https://github.com/csurally/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%20Arts%20%26%20Crafts/resources/stylesheet.css#L29-L33

You're repeating the `font-family` style in several CSS rules. It would be better to write that single shared style into a single CSS rule with multiple selectors.

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```

Or, since every element on this page should have the same font, you can just use the universal selector `*`.

```css
* {
  font-family: Helvetica;
}
```
